name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: sms-service
  IMAGE_TAG: latest
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{REGISTRY}}/${{ github.repository }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
